#!/bin/sh

# Upload this file as VULTR boot script.
# Check the URL and fill in the script id in the `activate` file.

# Firewall
ufw allow ssh
ufw allow 2376/tcp
ufw default deny incoming
ufw default allow outgoing
ufw enable

# Automatic security updates
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure unattended-upgrades

# Fail2ban
apt-get install -y fail2ban

# Disable ssh password authentication
grep -q "ChallengeResponseAuthentication" /etc/ssh/sshd_config && sed -i "/^[^#]*ChallengeResponseAuthentication[[:space:]]yes.*/c\ChallengeResponseAuthentication no" /etc/ssh/sshd_config || echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
grep -q "^[^#]*PasswordAuthentication" /etc/ssh/sshd_config && sed -i "/^[^#]*PasswordAuthentication[[:space:]]yes/c\PasswordAuthentication no" /etc/ssh/sshd_config || echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

service sshd restart
